-- 코드를 입력하세요
SELECT c.CAR_ID,
       c.CAR_TYPE, 
       ROUND(c.DAILY_FEE * 30 * (1 - p.DISCOUNT_RATE/100), 0) FEE
FROM CAR_RENTAL_COMPANY_CAR c 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
ON c.CAR_TYPE=p.CAR_TYPE
WHERE c.CAR_TYPE IN ("세단", "SUV") 
    AND c.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= "2022-11-30" AND END_DATE >= "2022-11-01"
    ) 
    AND p.DURATION_TYPE LIKE "30일%"
    AND ROUND(c.DAILY_FEE * 30 * (1 - p.DISCOUNT_RATE/100), 0) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC
