-- 코드를 입력하세요
SELECT u.USER_ID, 
       u.NICKNAME, 
       CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', u.STREET_ADDRESS2) "전체주소", 
       CONCAT(SUBSTR(u.TLNO, 1, 3), '-', SUBSTR(u.TLNO, 4, 4), '-', SUBSTR(u.TLNO, 8, 4)) "전화번호"
FROM USED_GOODS_USER u LEFT JOIN USED_GOODS_BOARD b on b.WRITER_ID=u.USER_ID
GROUP BY 1
HAVING COUNT(b.WRITER_ID) >= 3
ORDER BY u.USER_ID DESC