-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, u.GENDER, COUNT(DISTINCT u.USER_ID) USERS
FROM USER_INFO u JOIN ONLINE_SALE o on u.USER_ID=o.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY YEAR, MONTH, u.GENDER