-- 코드를 입력하세요
WITH USER_JOIN AS (
    SELECT COUNT(*) COUNT_USER
    FROM USER_INFO
    WHERE JOINED LIKE "2021%"
)

SELECT YEAR(o.SALES_DATE) YEAR, 
       MONTH(o.SALES_DATE) MONTH, 
       COUNT(DISTINCT o.USER_ID) PURCHASED_USERS, 
       ROUND(COUNT(DISTINCT o.USER_ID) / u.COUNT_USER, 1) PURCHASED_RATIO
FROM ONLINE_SALE o 
JOIN USER_JOIN u
WHERE o.USER_ID IN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE "2021%"
)
GROUP BY YEAR(o.SALES_DATE) , MONTH(o.SALES_DATE)
ORDER BY YEAR(o.SALES_DATE) , MONTH(o.SALES_DATE)