-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(p.PRICE * o.AMOUNT) TOTAL_SALES 
FROM FOOD_PRODUCT p LEFT JOIN FOOD_ORDER o on p.PRODUCT_ID=o.PRODUCT_ID 
WHERE o.PRODUCE_DATE LIKE "2022-05%"
GROUP BY 2
ORDER BY SUM(p.PRICE * o.AMOUNT) DESC, p.PRODUCT_ID