-- 코드를 입력하세요
SELECT a.APNT_NO, p.PT_NAME, a.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM PATIENT p LEFT JOIN APPOINTMENT a ON p.PT_NO=a.PT_NO LEFT JOIN DOCTOR d ON a.MDDR_ID=d.DR_ID
WHERE a.APNT_YMD LIKE "2022-04-13%" AND a.APNT_CNCL_YN = "N" AND a.MCDP_CD = "CS"
ORDER BY a.APNT_YMD