-- 코드를 입력하세요
WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM HOUR_TABLE
    WHERE HOUR < 23
)

SELECT h.HOUR, COUNT(ANIMAL_ID) COUNT
FROM HOUR_TABLE h 
LEFT JOIN (
    SELECT HOUR(DATETIME) HOUR, ANIMAL_ID
    FROM ANIMAL_OUTS
) a
ON h.HOUR=a.HOUR
GROUP BY h.HOUR
ORDER BY h.HOUR