-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD b LEFT JOIN USED_GOODS_USER u on b.WRITER_ID=u.USER_ID
WHERE STATUS LIKE "DONE"
GROUP BY b.WRITER_ID 
HAVING SUM(b.PRICE) >= 700000
ORDER BY SUM(b.PRICE)
