-- 코드를 입력하세요
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE m JOIN REST_REVIEW r ON m.MEMBER_ID=r.MEMBER_ID
WHERE m.MEMBER_ID = (
    SELECT m.MEMBER_ID
    FROM MEMBER_PROFILE m JOIN REST_REVIEW r ON m.MEMBER_ID=r.MEMBER_ID
    GROUP BY m.MEMBER_ID
    ORDER BY COUNT(m.MEMBER_ID) DESC LIMIT 1    
)
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT 