-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", b.BOARD_ID, "/", f.FILE_ID, f.FILE_NAME, f.FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD b JOIN USED_GOODS_FILE f on b.BOARD_ID=f.BOARD_ID
WHERE b.VIEWS IN (
    SELECT MAX(b.VIEWS)
    FROM USED_GOODS_BOARD b JOIN USED_GOODS_FILE f on b.BOARD_ID=f.BOARD_ID
)
ORDER BY f.FILE_ID DESC